### ISSUE TITLE
A CSL processor?

### ISSUE THREAD

**Issue by leeper** [ropensci/csl#1]
Is the plan to build this out to be a full [CSL processor](http://citationstyles.org/developers/#CSL_Processors) or is it only meant as a parser?

**Comment by sckott** [comment]
@leeper the goal of this is to mirror https://github.com/inukshuk/csl-ruby - that I think just imports and parses CSL styles

that gem does allow creation of new styles, which could do here, but I can't image people using R to create styles?

in another pkg, i was going to implement a complete CSL processor

**Comment by sckott** [comment]
whereas the ruby gem `csl-ruby` has a separate gem for styles https://github.com/inukshuk/csl-styles i thought that functionality should just go in this pkg  (files are too big to keep in pkg, but could have a script do the download)

**Comment by leeper** [comment]
Okay, very exciting! I also doubt anyone would use R to create new styles.

**Comment by sckott** [comment]
ok, closing
